options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _REPO: async
  _CLUSTER: async-cluster
  _NAMESPACE: async-doctor

steps:
# Auth to Artifact Registry for docker
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      gcloud auth configure-docker ${_REGION}-docker.pkg.dev -q

# Build images
- name: gcr.io/cloud-builders/docker
  dir: server
  args:
    [
      "build","-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/server:${SHORT_SHA}",
      "."
    ]

- name: gcr.io/cloud-builders/docker
  dir: web
  args:
    [
      "build","-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/web:${SHORT_SHA}",
      "--build-arg","VITE_API_BASE=/api",
      "."
    ]

# Push images
- name: gcr.io/cloud-builders/docker
  args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/server:${SHORT_SHA}"]

- name: gcr.io/cloud-builders/docker
  args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/web:${SHORT_SHA}"]

# Fetch cluster credentials
- name: gcr.io/cloud-builders/gcloud
  args:
    [
      "container","clusters","get-credentials","${_CLUSTER}",
      "--region","${_REGION}","--project","$PROJECT_ID"
    ]

# Substitute images in k8s yamls (REG/PROJ/REPO/SHORT_SHA)
# Substitute images in k8s yamls
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      IMG_BASE="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}"
      find k8s -type f -name '*.yaml' -print0 | xargs -0 sed -i \
        -e "s#REG-docker.pkg.dev/PROJ/REPO/server:SHORT_SHA#$$IMG_BASE/server:${SHORT_SHA}#g" \
        -e "s#REG-docker.pkg.dev/PROJ/REPO/web:SHORT_SHA#$$IMG_BASE/web:${SHORT_SHA}#g"


# Apply manifests
- name: gcr.io/cloud-builders/kubectl
  args: ["apply","-f","k8s/namespace.yaml","-f","k8s/pvc.yaml","-f","k8s/config.yaml"]
  env:
    - "CLOUDSDK_COMPUTE_REGION=${_REGION}"
    - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"

- name: gcr.io/cloud-builders/kubectl
  args: ["apply","-f","k8s/server.deployment.yaml","-f","k8s/server.service.yaml","-f","k8s/web.deployment.yaml","-f","k8s/web.service.yaml","-f","k8s/ingress.yaml"]
  env:
    - "CLOUDSDK_COMPUTE_REGION=${_REGION}"
    - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"

images:
- "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/server:${SHORT_SHA}"
- "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/web:${SHORT_SHA}"
